name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu

    steps:
    - uses: actions/checkout@v2
      
    - name: make 
      run:  make -C 3_Implementation
